version: '3'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    driver: local

